version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
    - "8081:8081"
    depends_on:
      - db
    environment:
      #- SPRING_SQL_INIT_MODE=always
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/orcl
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=password1

  db:
    image: oracle/database:21.3.0-se2
    container_name: db
    ports:
    - "8082:1521"
    environment:
      - ORACLE_SID=orcl
      - ORACLE_PDB=oracle_dba
      - ORACLE_PWD=password1